### data
smiles_col: "SMILES"
target_col_prefix: "TARGET"
target_normalize: "auto"
anomaly_clean: False
smi_strict: False
### model
model_name: "unimolv1"
### trainer
split_method: "5fold_random" 
split_seed: 42
seed: 42
logger_level: 1
patience: 10
max_epochs: 300
learning_rate: 1e-4
warmup_ratio: 0.03
batch_size: 64
max_norm: 5.0
use_cuda: True
use_amp: True
use_ddp: True
use_gpu: 0, 1
task: regression  # 明确任务类型
metrics: mae,rmse,mse,r2  # 回归任务评估指标
output_size: 1      # 输出维度为1
loss: mse           # 回归损失函数